### ISSUE TITLE
Can't run ddh from the desktop

### ISSUE THREAD

**Issue by GMaynard1** [LowellInstruments/ddt#5]
```
R > calling DDH GUI main python code

R > bluetooth power check
Can't get device info: No such device

R > bluetooth sanity check
Can't get device info: No such device

R > ensure rfkill wlan unblock

R > permissions date / ifmetric
Failed to set capabilities on file `/usr/sbin/ifmetric' (No such file or directory)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file

R > calling DDS main python code
Traceback (most recent call last):
  File "/home/pi/li/venv/lib/python3.9/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/home/pi/li/venv/lib/python3.9/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/pi/li/venv/lib/python3.9/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libcblas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/li/ddh/main_dds.py", line 7, in <module>
    from dds.aws import aws_serve
  File "/home/pi/li/ddh/dds/aws.py", line 11, in <module>
    from dds.emolt import this_box_has_grouped_s3_uplink
  File "/home/pi/li/ddh/dds/emolt.py", line 3, in <module>
    from mat.utils import linux_is_rpi
  File "/home/pi/li/venv/lib/python3.9/site-packages/mat/utils.py", line 9, in <module>
    from numpy import array, mod
  File "/home/pi/li/venv/lib/python3.9/site-packages/numpy/__init__.py", line 141, in <module>
    from . import core
  File "/home/pi/li/venv/lib/python3.9/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/home/pi/li/venv/bin/python"
  * The NumPy version is: "1.24.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libcblas.so.3: cannot open shared object file: No such file or directory

Traceback (most recent call last):
  File "/home/pi/li/venv/lib/python3.9/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/home/pi/li/venv/lib/python3.9/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/pi/li/venv/lib/python3.9/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libcblas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/li/ddh/main_ddh.py", line 7, in <module>
    from ddh.gui.main_gui import DDH, on_ctrl_c
  File "/home/pi/li/ddh/ddh/gui/main_gui.py", line 2, in <module>
    import pyqtgraph as pg
  File "/home/pi/li/venv/lib/python3.9/site-packages/pyqtgraph/__init__.py", line 14, in <module>
    import numpy  # # pyqtgraph requires numpy
  File "/home/pi/li/venv/lib/python3.9/site-packages/numpy/__init__.py", line 141, in <module>
    from . import core
  File "/home/pi/li/venv/lib/python3.9/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/home/pi/li/venv/bin/python"
  * The NumPy version is: "1.24.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libcblas.so.3: cannot open shared object file: No such file or directory

$F_VE/bin/python main_ddh.py TRAPPED! rv 1
```

**Comment by GMaynard1** [comment]
Tried installing numpy manually, but still getting the error. I will try to reinstall the system from the beginning.

**Comment by kazola** [comment]
need to run ./dt_install_linux.sh first
